all: part-1 part-2

# options:
# -Wall: all warnings
# -W: additional warnings
# -pedantic: strict compliance with the C standard
# -O2: (O)ptimization level 2
part-1: 1.c
	$(CC) 1.c -Wall -W -pedantic -O2 -o part-1

part-2: 2.c
	$(CC) 2.c -Wall -W -pedantic -O2 -o part-2

clean:
	rm -rf part-1 part-2
